package app.threedollars.manager.vo

data class BossEnumsVo(
    val paymentMethodType: List<EnumsVo> = listOf(),
    val bossStoreOpenType: List<EnumsVo> = listOf(),
    val feedbackTargetType: List<EnumsVo> = listOf(),
    val advertisementPositionType: List<EnumsVo> = listOf(),
    val userMenuCategoryType: List<EnumsVo> = listOf(),
    val pushPlatformType: List<EnumsVo> = listOf(),
    val bossRegistrationStatus: List<EnumsVo> = listOf(),
    val storeType: List<EnumsVo> = listOf(),
    val applicationType: List<EnumsVo> = listOf(),
    val dayOfTheWeek: List<EnumsVo> = listOf(),
    val pushOptionsType: List<EnumsVo> = listOf(),
    val fileType: List<EnumsVo> = listOf(),
    val bossAccountSocialType: List<EnumsVo> = listOf(),
    val boosRegistrationRejectReasonType: List<EnumsVo> = listOf(),
    val deleteReasonType: List<EnumsVo> = listOf(),
    val visitType: List<EnumsVo> = listOf(),
    val faqCategory: List<EnumsVo> = listOf(),
    val storeSalesType: List<EnumsVo> = listOf(),
    val userSocialType: List<EnumsVo> = listOf(),
    val feedbackEmojiType: List<EnumsVo> = listOf(),
    val bankType: List<EnumsVo> = listOf(),
)
