name: 'Firebase App Distribution'
on:
  push:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 # This is optional on linux and macOS
        with:
          node-version: '14'
      - uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{secrets.FIREBASE_TOKEN}}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Retrieve version
        run: echo "::set-output name=VERSION_NAME::$(grep -i "versionName " app/build.gradle.kts | awk '{print $3}')" | tr -d '"'
        id: version

      - name: Read release note
        id: release_note
        run: echo "::set-output name=RELEASE_NOTE::$(cat ./release_note.txt)"

      - name: Create google-service.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
        id: google-service

      - name: Create local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIRES }}' > ./local.properties
        id: propertie

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload artifact to Firebase App Distribution
        run: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --token ${{secrets.FIREBASE_TOKEN}} --app ${{secrets.FIREBASE_APP_ID}} --groups "android" --release-notes-file "./release_note.txt"

      - name: Deploy APK to Slack
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: 'C01EUAT55CJ'
          file_path: 'app/build/outputs/apk/debug/app-debug.apk'
          file_name: 'app-debug.apk'
          file_type: 'apk'

      - name: Action-slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          text: "Firebase Distribution에 새로운 APK가 올라왔습니다! :smile:\nversion : ${{ steps.version.outputs.VERSION_NAME }}\nrelease note : ${{ steps.release_note.outputs.RELEASE_NOTE }}"
          fields: ref, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}